# Generated by Django 3.1.2 on 2020-11-11 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('badge_id', models.CharField(blank=True, max_length=30)),
                ('checked_in', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_room', models.CharField(max_length=30)),
                ('meeting_desc', models.CharField(max_length=200)),
                ('time_slot', models.DateTimeField()),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.guest')),
            ],
        ),
    ]
