# Generated by Django 3.1.2 on 2020-11-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=30)),
                ('meeting_title', models.CharField(max_length=30)),
                ('meeting_desc', models.CharField(max_length=200)),
                ('time_slot', models.DateTimeField()),
            ],
        ),
    ]
