# Generated by Django 3.1.2 on 2020-11-06 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('badge_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='guest_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.guest'),
        ),
    ]
