# Generated by Django 3.1.2 on 2020-11-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201106_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='guest_name',
            new_name='guest',
        ),
    ]
