# Generated by Django 3.1.2 on 2020-11-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201106_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='guest',
        ),
        migrations.AddField(
            model_name='meeting',
            name='guest',
            field=models.ManyToManyField(to='pages.Guest'),
        ),
    ]
