# Generated by Django 3.1.3 on 2020-11-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_guest_checked_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_title',
            new_name='meeting_room',
        ),
        migrations.AlterField(
            model_name='guest',
            name='badge_id',
            field=models.CharField(max_length=30),
        ),
    ]
