# Generated by Django 3.1.2 on 2020-11-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201110_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='badge_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
